function [M,C,Gv] = dinamica_v1_gen(phi,l,dphi,dl,m_b,m_w,J_b,g,alpha)
%DINAMICA_V1_GEN
%    [M,C,Gv] = DINAMICA_V1_GEN(PHI,L,DPHI,DL,M_B,M_W,J_b,G,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    02-Sep-2026 18:09:07

M = reshape([m_b+m_w,l.*m_b.*cos(phi),m_b.*sin(phi),l.*m_b.*cos(phi),J_b+l.^2.*m_b,0.0,m_b.*sin(phi),0.0,m_b],[3,3]);
if nargout > 1
    C = [dphi.*m_b.*(dl.*cos(phi).*2.0-dphi.*l.*sin(phi));dl.*dphi.*l.*m_b.*2.0;-dphi.^2.*l.*m_b];
end
if nargout > 2
    Gv = [g.*sin(alpha).*(m_b+m_w);g.*l.*m_b.*sin(alpha-phi);g.*m_b.*cos(alpha-phi)];
end
end
